### ISSUE TITLE
Leverage namespace package

### ISSUE THREAD

**Issue by reyang** [orijtech/ocspymemcached#4]
Please refer to https://github.com/census-instrumentation/opencensus-python/issues/445 and https://github.com/census-instrumentation/opencensus-python/commit/ff80d11801b78a4242080f55d22bb77e6434164c.

We would want to have all the integrations following the same pattern:
1. Package name: opencensus-ext-memcached.
2. Namespace: opencensus.ext.memcached.

**Comment by odeke-em** [comment]
Thanks for filing this issue @reyang! Unfortunately this isn't a Python project, it is a Java project :)

But also currently this project is published on Maven Central https://mvnrepository.com/artifact/io.orijtech.integrations/ocspymemcached under my namespace.

**Comment by reyang** [comment]
Ah, sorry! I was looking at https://pypi.org/project/ocpymemcache/.
